hexadash-django/hexadash/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('list', views.all, name='customer_list'),
    path('create', views.create, name='new_customer'),
    path('store', views.store, name='store'),
    path('edit/<int:id>', views.show, name='show'),
    path('update/<int:id>', views.update, name='update'),
    path('destroy/<int:id>', views.destroy, name='destroy'),
]

hexadash-django/hexadash/hexadash_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_register.urls')),
]

urlpatterns += i18n_patterns(
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('application/', include('application.urls', namespace='application')),
    path('ui/', include('ui.urls', namespace='ui')),
    path('feature/', include('feature.urls', namespace='feature')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('customer/', include('customer.urls', namespace='customer')),    
)

hexadash-django/hexadash/ui/urls.py
from django.urls import path
from . import views

app_name = 'ui'

urlpatterns = [
    path('alert', views.alert, name='alert'),
    path('avatar', views.avatar, name='avatar'),
    path('badge', views.badge, name='badge'),
    path('breadcrumb', views.breadcrumb, name='breadcrumb'),
    path('button', views.button, name='button'),
    path('card', views.card, name='card'),
    path('carousel', views.carousel, name='carousel'),
    path('checkbox', views.checkbox, name='checkbox'),
    path('collapse', views.collapse, name='collapse'),
    path('comments', views.comment, name='comment'),
    path('dashboard-base', views.dashboard_base, name='dashboard_base'),
    path('datepicker', views.datepicker, name='datepicker'),
    path('drawer', views.drawer, name='drawer'),
    path('drag-drop', views.drag_drop, name='drag_drop'),
    path('dropdown', views.dropdown, name='dropdown'),
    path('empty', views.empty, name='empty'),
    path('grid', views.grid, name='grid'),
    path('input', views.input, name='input'),
    path('list', views.list, name='list'),
    path('menu', views.menu, name='menu'),
    path('message', views.message, name='message'),
    path('modals', views.modals, name='modals'),
    path('notifications', views.notifications, name='notifications'),
    path('page-header', views.pageHeader, name='page_header'),
    path('paginations', views.paginations, name='paginations'),
    path('progress', views.progress, name='progress'),
    path('radio', views.radio, name='radio'),
    path('rate', views.rate, name='rate'),
    path('result', views.result, name='result'),
    path('select', views.select, name='select'),
    path('skeleton', views.skeleton, name='skeleton'),
    path('slider', views.slider, name='slider'),
    path('spinner', views.spinner, name='spinner'),
    path('statistic', views.statistic, name='statistic'),
    path('steps', views.steps, name='steps'),
    path('switch', views.switch, name='switch'),
    path('tabs', views.tabs, name='tabs'),
    path('tag', views.tag, name='tag'),
    path('timeline', views.timeline, name='timeline'),
    path('timeline2', views.timeline2, name='timeline2'),
    path('timeline3', views.timeline3, name='timeline3'),
    path('timepicker', views.timepicker, name='timepicker'),
    path('upload', views.upload, name='upload'),
]

hexadash-django/hexadash/customer/models.py
""" from turtle import position """
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=255, blank=False)
    email = models.EmailField(max_length=255, blank=False, unique=True)
    phone = models.CharField(max_length=255, blank=False, unique=True)
    countryOption = models.CharField(max_length=255, blank=False)
    cityOption = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=255, blank=True)
    position = models.CharField(max_length=255, blank=True)
    join = models.CharField(max_length=255, blank=True)
    status = models.CharField(max_length=255, null=False)
    image = models.TextField(blank=True)

    class Meta:
        db_table = 'customers'


hexadash-django/hexadash/customer/forms.py
from django import forms
from .models import Customer

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','email','phone','countryOption','cityOption','company', 'position', 'join', 'status', 'image']

class CustomerEditForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','countryOption','cityOption','company', 'position', 'join', 'status', 'image']

hexadash-django/hexadash/customer/views.py
from django.shortcuts import redirect, render
from customer.models import Customer
from .forms import CustomerForm, CustomerEditForm
from django.contrib.auth.decorators import login_required

# customer list
@login_required
def all(request):
    customers = Customer.objects.all()
    count_customers = len(customers)
    return render(request, 'customer/list.html',{'customers':customers,'count_customers':count_customers})

# new customer
@login_required
def create(request):
    return render(request, 'customer/create.html')

# insert customer
@login_required
def store(request):
    if request.method == 'POST':
        customer = CustomerForm(request.POST)
        if customer.is_valid():
            customer.save()
            return redirect('/customer/list')            
        else:           
            return render(request, 'customer/create.html', {'form': customer})

# show customer by id
@login_required
def show(request, id):
    customer = Customer.objects.get(id=id)
    return render(request, 'customer/edit.html',{'customer':customer})

# update customer
@login_required
def update(request, id):
    customer = Customer.objects.get(id=id)
    if request.method == 'POST':
        customerForm = CustomerEditForm(request.POST, instance=customer)
        if customerForm.is_valid():
            customerForm.save()
            return redirect('/customer/list')
        else:            
            return render(request, 'customer/edit.html',{'customer':customer, 'form': customerForm})

# delete customer
@login_required
def destroy(request, id):
    customer = Customer.objects.get(id=id)
    customer.delete()
    return redirect('/customer/list')

hexadash-django/hexadash/templates/customer/create.html
{% extends 'layout/app.html' %}

{% block title %} New Customer {% endblock %}

{% load i18n %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-breadcrumb">

                <div class="breadcrumb-main add-contact justify-content-sm-between ">
                    <div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
                        <div class="d-flex align-items-center add-contact__title justify-content-center me-sm-25">
                            <h4 class="text-capitalize fw-500 breadcrumb-title">Add User</h4>
                            <span class="sub-title ms-sm-25 ps-sm-25"></span>
                        </div>
                        <div class="action-btn mt-sm-0 mt-15">
                            <a href="{% url 'customer:customer_list' %}" class="btn px-20 btn-primary ">
                                View All
                            </a>
                        </div>
                    </div>
                    
                </div>

            </div>
            <!-- ends: contact-breadcrumb -->
        </div>
    </div>
    <div class="card mb-50">
        <div class="row justify-content-center">
            <div class="col-md-5 col-10">
                <div class="mt-40 mb-50">
                    <div class="account-profile d-flex align-items-center mb-4 ">
                        <div class="ap-img pro_img_wrapper">
                            <input id="file-upload" type="file" name="fileUpload" class="d-none">
                            <!-- Profile picture image-->
                            <label for="file-upload">
                                <img class="ap-img__main rounded-circle wh-120 bg-lighter d-flex" id="previewImg" src="{% static 'img/author/profile.png' %}" alt="profile">
                                <span class="cross" id="remove_pro_pic">
                                    <img src="{% static 'img/svg/camera.svg' %}" alt="camera" class="svg">
                                </span>
                            </label>
                        </div>
                        <div class="account-profile__title">
                            <h6 class="fs-15 ms-20 fw-500 text-capitalize">profile photo</h6>
                        </div>
                    </div>
                    <div class="edit-profile__body">
                        <form action="{% url 'customer:store' %}" method="POST">
                            {% csrf_token %}
                            
                            <input type="hidden" id="image" name="image" value="">
                            <div class="form-group mb-25">
                                <label for="name">name <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Duran Clayton">
                                {% if form and form.errors.name %} <div class="text-danger mt-2">{{form.errors.name}}</div> {% else %} {% endif %} 
                            </div>
                            <div class="form-group mb-25">
                                <label for="email">Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="sample@email.com">
                                {% if form and form.errors.email %} <div class="text-danger mt-2">{{form.errors.email}}</div> {% else %} {% endif %}                                                        
                            </div>
                            <div class="form-group mb-25">
                                <label for="phone">phone number <span class="text-danger">*</span></label>
                                <input type="tel" class="form-control" id="phone" name="phone" placeholder="+440 2546 5236">  
                                {% if form and form.errors.phone %} <div class="text-danger mt-2">{{form.errors.phone}}</div> {% else %} {% endif %}                               
                            </div>
                            <div class="form-group mb-25">
                                <div class="countryOption">
                                    <label for="countryOption">
                                        country <span class="text-danger">*</span>
                                    </label>
                                    <select class="js-example-basic-single js-states form-control" id="countryOption" name="countryOption">
                                        <option value="">Select Country</option>
                                        <option value="Bangladash">Bangladash</option>
                                        <option value="India">India</option>
                                        <option value="Pakistan">Pakistan</option>
                                    </select>   
                                    {% if form and form.errors.countryOption %} <div class="text-danger mt-2">{{form.errors.countryOption}}</div> {% else %} {% endif %}   
                                </div> 
                            </div>
                            <div class="form-group mb-25">
                                <div class="cityOption">
                                    <label for="cityOption">
                                        City 
                                    </label>
                                    <select class="js-example-basic-single js-states form-control" id="cityOption" name="cityOption">
                                        <option value="">Select City</option>
                                        <option value="Dhaka">Dhaka</option>
                                        <option value="Barisal">Barisal</option>
                                        <option value="Sylet">Sylet</option>
                                    </select>   
                                    {% if form and form.errors.cityOption %} <div class="text-danger mt-2">{{form.errors.cityOption}}</div> {% else %} {% endif %}                              
                                </div>                               
                            </div>
                            <div class="form-group mb-25">
                                <label for="company">Company name </label>
                                <input type="text" class="form-control" id="company" name="company" placeholder="Example">
                                {% if form and form.errors.company %} <div class="text-danger mt-2">{{form.errors.company}}</div> {% else %} {% endif %} 
                            </div>
                            <div class="form-group mb-25">
                                <label for="position">Position</label>
                                <input type="text" class="form-control" id="position" name="position" placeholder="Position">   
                                {% if form and form.errors.position %} <div class="text-danger mt-2">{{form.errors.position}}</div> {% else %} {% endif %}                              
                            </div>
                            <div class="form-group mb-25 form-group-calender">
                                <label for="datepicker">Joining Date</label>
                                <div class="position-relative">
                                    <input type="text" class="form-control" id="datepicker" name="join" placeholder="Select date">
                                    <a href="#"><img class="svg" src="{% static 'img/svg/calendar.svg' %}" alt="calendar"></a>
                                    {% if form and form.errors.join %} <div class="text-danger mt-2">{{form.errors.join}}</div> {% else %} {% endif %} 
                                </div>                                
                            </div>
                            <div class="form-group mb-25 status-radio">
                                <label class="mb-15" for="phoneNumber2">status</label>
                                <div class="d-flex">
                                    <div class="radio-horizontal-list d-flex flex-wrap">
                                        <div class="radio-theme-default custom-radio ">
                                            <input class="radio" type="radio" checked name="status" value="active" id="radio-hl1">
                                            <label for="radio-hl1">
                                                <span class="radio-text">active</span>
                                            </label>
                                        </div>
                                        <div class="radio-theme-default custom-radio ">
                                            <input class="radio" type="radio" name="status" value="deactivate" id="radio-hl2">
                                            <label for="radio-hl2">
                                                <span class="radio-text">Deactivated</span>
                                            </label>
                                        </div>
                                        <div class="radio-theme-default custom-radio ">
                                            <input class="radio" type="radio" name="status" value="blocked" id="radio-hl3">
                                            <label for="radio-hl3">
                                                <span class="radio-text">bloked</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="button-group d-flex pt-25 justify-content-md-end justify-content-start">
                                <button class="btn btn-primary btn-default btn-squared text-capitalize radius-md shadow2 btn-sm">Submit
                                </button>
                            </div>                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>                      
</div>
<script>
    var getImg = document.getElementById('file-upload');

    function openFile (file) {
        var input = file.target;

        var reader = new FileReader();
        reader.onload = function(){
            var dataURL = reader.result;      
            document.getElementById('previewImg').src = dataURL;              
            document.getElementById('image').value = dataURL;              
        };
        reader.readAsDataURL(input.files[0]);
    };
    
    getImg.addEventListener('change', openFile)
</script>

{% endblock %}

hexadash-django/hexadash/templates/customer/list.html
{% extends 'layout/app.html' %}

{% block title %} Customer List {% endblock %}

{% load i18n %}

{% load static %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-breadcrumb">

                <div class="breadcrumb-main add-contact justify-content-sm-between ">
                    <div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
                        <div class="d-flex align-items-center add-contact__title justify-content-center me-sm-25">
                            <h4 class="text-capitalize fw-500 breadcrumb-title">Data List</h4>
                            <span class="sub-title ms-sm-25 ps-sm-25"></span>
                        </div>
                        <div class="action-btn mt-sm-0 mt-15">
                            <a href="{% url 'customer:new_customer' %}" class="btn px-20 btn-primary ">
                                <i class="las la-plus fs-16"></i>Add New
                            </a>
                        </div>
                    </div>
                    <div class="breadcrumb-main__wrapper">

                        <form action="/" class="d-flex align-items-center add-contact__form my-sm-0 my-2">
                            <img src="{% static 'img/svg/search.svg' %}" alt="search" class="svg">
                            <input class="form-control me-sm-2 border-0 box-shadow-none" type="search" placeholder="Search by Name" aria-label="Search">
                        </form>

                    </div>
                </div>

            </div>
            <!-- ends: contact-breadcrumb -->
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 mb-30">
            <div class="card">
                <div class="card-header color-dark fw-500">
                    User List
                </div>
                <div class="card-body">

                    <div class="userDatatable global-shadow border-light-0 w-100">
                        <div class="table-responsive">
                            <table class="table mb-0 table-borderless">
                                <thead>
                                    <tr class="userDatatable-header">
                                        <th>
                                            <div class="d-flex align-items-center">
                                                <div class="custom-checkbox  check-all">
                                                    <input class="checkbox" type="checkbox" id="check-45">
                                                    <label for="check-45">
                                                        <span class="checkbox-text userDatatable-title">user</span>
                                                    </label>
                                                </div>
                                            </div>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">Email</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">phone</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">company</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">position</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">join date</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title">status</span>
                                        </th>
                                        <th>
                                            <span class="userDatatable-title float-end">action</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if count_customers == 0 %}
                                        <tr>
                                            <td colspan="7"><p class="text-center">No Customer Found !</p></td>
                                         </tr>
                                    {% else %}
                                    {% for customer in customers %}
                                    <tr>
                                        <td>
                                            <div class="d-flex">
                                                <div class="userDatatable__imgWrapper d-flex align-items-center">
                                                    <div class="checkbox-group-wrapper">
                                                        <div class="checkbox-group d-flex">
                                                            <div class="checkbox-theme-default custom-checkbox checkbox-group__single d-flex">
                                                                <input class="checkbox" type="checkbox" id="check-grp-<%- index %>">
                                                                <label for="check-grp-<%- index %>"></label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <a href="#" class="profile-image rounded-circle d-block m-0 wh-38" style="background-image:url('{% if customer.image %} {{customer.image}} {% else %} {% static "img/author/profile.png" %}{% endif %}'); background-size: cover;"></a>
                                                </div>
                                                <div class="userDatatable-inline-title">
                                                    <a href="#" class="text-dark fw-500">
                                                        <h6>{{ customer.name }}</h6>
                                                    </a>
                                                    <p class="d-block mb-0">
                                                        {{ customer.countryOption }}                                                       
                                                    </p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content">
                                                {{ customer.email }}                                                  
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content">
                                                {{ customer.phone }}                                                      
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content">
                                                {{ customer.company }}      
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content">
                                                {{ customer.position }}      
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content">
                                                {{ customer.join }}      
                                            </div>
                                        </td>
                                        <td>
                                            <div class="userDatatable-content d-inline-block">
                                                <span class="{% if customer.status == 'active' %} bg-opacity-success  color-success {% elif customer.status == 'deactivate' %} bg-opacity-warning  color-warning {% else %} bg-opacity-danger  color-danger {% endif %} rounded-pill userDatatable-content-status active">{{ customer.status }}</span>
                                            </div>
                                        </td>
                                        <td>
                                            <ul class="orderDatatable_actions mb-0 d-flex flex-wrap">
                                                <li>
                                                    <a href="#" class="view">
                                                        <i class="uil uil-eye"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{% url 'customer:show' customer.id %}" class="edit">
                                                        <i class="uil uil-edit"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#" onclick="
                                                    if(confirm('Are you sure you want to delete ?')){                                    
                                                       event.preventDefault();
                                                       document.getElementById('delete-{{ customer.id }}').submit();
                                                    }else{
                                                       event.preventDefault();
                                                    }
                                                 " class="remove">
                                                        <i class="uil uil-trash-alt"></i>
                                                    </a>
                                                    <form style="display:none;" id="delete-{{ customer.id }}" action="{% url 'customer:destroy' customer.id %}" method="POST">
                                                        {% csrf_token %}
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% endif %}       
                                </tbody>
                            </table>
                        </div>
                    </div>                        
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}